config/routes.rb
Rails.application.routes.draw do
  root to: 'blogs#index'
  resources :blogs do
    collection do
      post :confirm
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  #画像がある場合はcontentが空でもvalidatesが有効になる設定
  validates :content, presence: true, unless: :image?
  mount_uploader :image, ImageUploader
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, presence: true, uniqueness: true, length:{ maximum:100}
end

app/models/user.rb
class User < ApplicationRecord
  has_many :blogs
  validates :name,  presence: true, length: { maximum: 9 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  def index
    @blogs = Blog.all.order(id: "desc")
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(blog_params)
    @blog.user_id = current_user.id
    if params[:back]
      render :new
    else
      if @blog.save
        redirect_to blogs_path
      else
        render 'new'
      end
    end
  end

  def show
  end

  def edit
  end

  def destroy
    @blog.destroy
    redirect_to blogs_path
  end

  def update
    if @blog.update(blog_params)
      redirect_to blogs_path
    else
      render :edit
    end
  end

  def confirm
    @blog = Blog.new(blog_params)
    @blog.user_id = current_user.id
    render :new if @blog.invalid?
  end

  private

  def blog_params
    params.require(:blog).permit(:content, :image, :image_cache)
  end

  def set_blog
    @blog = Blog.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to blogs_path
    else
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm' || action_name == 'create'
      confirm_blogs_path
    elsif action_name == 'edit'
      blog_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: @blog, local: true ,url: choose_new_or_edit ) do |form| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2>文章が画像どちらかを投稿して下さい！！</h2>
    </div>
  <% end %>
<div class="blog_content">
  <%= form.label :content %>
  <%= form.text_field :content %>
  </div>
  <div class="field">
  <%= form.label :image %>
  <%= form.file_field :image %>
  </div>
  <%= form.submit '投稿' %>
<% end %>
<br>
<%= link_to "戻る", blogs_path %>

app/views/blogs/confirm.html.erb
<header>
  <table>
    <tr>
      <td><%= image_tag "facebook.png", class: 'fakebook-logo' %></td>
      <td>
        <div class="fake-search-box">
          <div class="search-sujest">検索</div>
          <div class="search-content"></div>
          <div class="search-img"><%= image_tag "Search.png", class: 'search-png' %></div>
        </div>
      </td>
      <td><%= image_tag "acount-pic.png", size: '25x25', class: 'header-acount-pic' %></td>
      <td>
        <div class="header-menu">
          <% flash.each do |key, value| %>
            <%= content_tag(:div, value, class: "#{key}") %>
          <% end %>
          <span>
          <% if logged_in? %>
            <%= link_to "#{current_user.name}", user_path(current_user.id) %>
          </span>
          <span class="blue-line"> | </span>
          <span>
            <%= link_to "ホーム", blogs_path %>
          </span>
          <span class="blue-line"> | </span>
          <span>友達を検索</span>
          <span class="blue-line"> | </span>
          <span>作成</span>
          <span class="blue-line"> | </span>
          <span>うに</span>
          <span class="blue-line"> | </span>
          <span>
          <%= link_to "ログアウト", session_path(current_user.id), method: :delete %>
          <% else %>
            <%= link_to "登録", new_user_path %>
            <%= link_to "ログイン", new_session_path %>
          <% end %>
          </span>
        </div>
      </td>
    </tr>
  </table>
</header>

<main>
<div class="general-box">
  <h3>以下の内容で投稿しますか？</h3>
  <%= form_with(model: @blog, url: blogs_path, local: true) do |form| %>
    <%= form.hidden_field :content %>
    <p><%= @blog.content %></p>
    <%= image_tag(@blog.image.url) if @blog.image && @blog.image.url %>
    <%= form.hidden_field :image_cache %>
    <br>
    <br>
    <p><%= form.submit "はい" %><p/>
  <% end %>
  <%= form_with(model:@blog, url:new_blog_path, local:true, method:"get") do |form| %>
    <%= form.hidden_field :image_cache %>
    <p><%= form.submit "いいえ", name: "back" %><p/>
  <% end %>
</div>
</main>

app/views/blogs/edit.html.erb
<header>
  <table>
    <tr>
      <td><%= image_tag "facebook.png", class: 'fakebook-logo' %></td>
      <td>
        <div class="fake-search-box">
          <div class="search-sujest">検索</div>
          <div class="search-content"></div>
          <div class="search-img"><%= image_tag "Search.png", class: 'search-png' %></div>
        </div>
      </td>
      <td><%= image_tag "acount-pic.png", size: '25x25', class: 'header-acount-pic' %></td>
      <td>
        <div class="header-menu">
          <% flash.each do |key, value| %>
            <%= content_tag(:div, value, class: "#{key}") %>
          <% end %>
          <span>
          <% if logged_in? %>
            <%= link_to "#{current_user.name}", user_path(current_user.id) %>
          </span>
          <span class="blue-line"> | </span>
          <span>
            <%= link_to "ホーム", blogs_path %>
          </span>
          <span class="blue-line"> | </span>
          <span>友達を検索</span>
          <span class="blue-line"> | </span>
          <span>作成</span>
          <span class="blue-line"> | </span>
          <span>うに</span>
          <span class="blue-line"> | </span>
          <span>
          <%= link_to "Logout", session_path(current_user.id), method: :delete %>
          <% else %>
            <%= link_to "Sign up", new_user_path %>
            <%= link_to "Login", new_session_path %>
          <% end %>
          </span>
        </div>
      </td>
    </tr>
  </table>
</header>

<main>
  <div class="general-box">
    <h2>投稿を作成</h2>
    <%= render 'form' %>
  </div>
</main>

app/views/blogs/index.html.erb
<header>
  <table>
    <tr>
      <td><%= image_tag "facebook.png", class: 'fakebook-logo' %></td>
      <td>
        <div class="fake-search-box">
          <div class="search-sujest">検索</div>
          <div class="search-content"></div>
          <div class="search-img"><%= image_tag "Search.png", class: 'search-png' %></div>
        </div>
      </td>
      <td><%= image_tag "acount-pic.png", size: '25x25', class: 'header-acount-pic' %></td>
      <td>
        <div class="header-menu">
          <% flash.each do |key, value| %>
            <%= content_tag(:div, value, class: "#{key}") %>
          <% end %>
          <span>
          <% if logged_in? %>
            <%= link_to "#{current_user.name}", user_path(current_user.id) %>
          </span>
          <span class="blue-line"> | </span>
          <span>
            <%= link_to "ホーム", blogs_path %>
          </span>
          <span class="blue-line"> | </span>
          <span>友達を検索</span>
          <span class="blue-line"> | </span>
          <span>作成</span>
          <span class="blue-line"> | </span>
          <span>うに</span>
          <span class="blue-line"> | </span>
          <span>
          <%= link_to "ログアウト", session_path(current_user.id), method: :delete %>
          <% else %>
            <%= link_to "登録", new_user_path %>
            <%= link_to "ログイン", new_session_path %>
          <% end %>
          </span>
        </div>
      </td>
    </tr>
  </table>
</header>

<main>
  <div class="main-block">
    <div class="main-block-left">
      <%= image_tag "acount-pic.png", size: '20x20', class: 'left-acount-pic' %>
      <%= link_to "#{current_user.name}", user_path(current_user.id) %><br>
      <br>
      <div class="left-box-focus">
        <%= image_tag "newsfeed.png", size: '20x20' %>
        <span>ニュースフィード</span>
        <%= image_tag "reader.png", size: '20x20', class: 'left-reader' %>
      </div>
      <div class="left-box-unfocus">
        <%= image_tag "messenger.png", size: '20x20' %>
        <span>Messenger</span>
      </div>
      <div class="left-box-unfocus-alt">
        <%= image_tag "watch.png", size: '20x20' %>
        <span>Watch</span>
      </div>
      <div class="discover">発見</div>
      <div class="left-box-unfocus-alt">
        <%= image_tag "footprint.png", size: '20x20' %>
        <span>グループ</span>
      </div>
      <div class="left-box-unfocus-alt">
        <%= image_tag "flag.png", size: '20x20' %>
        <span>ページ</span>
      </div>
      <div class="left-box-unfocus-alt">
        <%= image_tag "calender.png", size: '20x20' %>
        <span>イベント</span>
      </div>
      <div class="left-box-unfocus-alt">
        <%= image_tag "coin.png", size: '20x20' %>
        <span>募金キャンペーン</span>
      </div>
      <div class="left-box-unfocus-alt">
        <%= image_tag "manekineko.png", size: '20x20' %>
        <span>友達一覧</span>
      </div>
      <div class="left-box-more">
        <%= image_tag "triangle.png", size: '10x5' %>
        <span>もっと見る...</span>
      </div>
    </div>
    <div class="main-block-center">
      <div class="main-box-new">
        &nbsp;&nbsp;
        <button type="button" class="btn btn-primary">
          <%= link_to '投稿を作成する', new_blog_path %>
        </button>
      </div>
      <% @blogs.each do |blog| %>
      <div class="main-box">
        <table>
          <tr>
            <td><%= image_tag "acount-pic.png", size: '40x40', class: 'box-acount-pic' %></td>
            <td>
            <div class="box-name"><%= blog.user.name %></div>
            <div class="box-time"><%= blog.created_at.try(:strftime,"%m月%d日") %></div>
            </td>
            <td class="detail"><%= link_to '詳細', blog_path(blog.id) %></td>
            <td><%= link_to "編集", edit_blog_path(blog.id) %></td>
            <td>
              <%= link_to '削除', blog_path(blog.id), method: :delete, data: { confirm: '本当に削除していいですか？' } %>
            </td>
          </tr>
        </table>
        <div class="box-content">
        <%= blog.content %>
        </div>
        <% if blog.image.file.nil? %>
          <% else %>
        <div class="box-pic">
          <%= image_tag blog.image.url %>
        </div>
        <% end %>
      </div>
      <% end %>
    </div>
    <div class="main-block-right">
      <span>おぬぬめグループ</span>
      <div class="recommend-group">
        <%= image_tag "snow.jpg", class: 'recommend-pic' %>
        <table>
          <tr>
            <td>
              <p class="blue-line">雪山をひたすら登る会</p>
              <p class="grey-line">メンバー1,950人</p>
            </td>
            <td>
              <div class="entry_btn">＋グループに参加</div>
            </td>
          </tr>
        </table>
      </div>
      <div class="recommend-group">
        <%= image_tag "yakitori.jpg", class: 'recommend-pic' %>
        <table>
          <tr>
            <td>
              <p class="blue-line">焼き鳥を食べまくるた</p>
              <p class="blue-line">めにわざわざ仕事まで</p>
              <p class="blue-line">休んでしまう人たち</p>
              <p class="grey-line">メンバー8,910人</p>
            </td>
            <td>
              <div class="entry_btn">＋グループに参加</div>
            </td>
          </tr>
        </table>
      </div>
      <div class="recommend-group">
        <%= image_tag "factory.jpg", class: 'recommend-pic' %>
        <table>
          <tr>
            <td>
              <p class="blue-line">工業地帯の夜景をもく</p>
              <p class="blue-line">もく撮影するグループ</p>
              <p class="grey-line">メンバー150人</p>
            </td>
            <td>
              <div class="entry_btn">＋グループに参加</div>
            </td>
          </tr>
        </table>
      </div>
      <div class="recommend-group">
        <%= image_tag "tea.jpg", class: 'recommend-pic' %>
        <table>
          <tr>
            <td>
              <p class="blue-line">紅茶をひたすら飲み隊</p>
              <p class="grey-line">メンバー70人</p>
            </td>
            <td>
              <div class="entry_btn">＋グループに参加</div>
            </td>
          </tr>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/blogs/new.html.erb
<header>
  <table>
    <tr>
      <td><%= image_tag "facebook.png", class: 'fakebook-logo' %></td>
      <td>
        <div class="fake-search-box">
          <div class="search-sujest">検索</div>
          <div class="search-content"></div>
          <div class="search-img"><%= image_tag "Search.png", class: 'search-png' %></div>
        </div>
      </td>
      <td><%= image_tag "acount-pic.png", size: '25x25', class: 'header-acount-pic' %></td>
      <td>
        <div class="header-menu">
          <% flash.each do |key, value| %>
            <%= content_tag(:div, value, class: "#{key}") %>
          <% end %>
          <span>
          <% if logged_in? %>
            <%= link_to "#{current_user.name}", user_path(current_user.id) %>
          </span>
          <span class="blue-line"> | </span>
          <span>
            <%= link_to "ホーム", blogs_path %>
          </span>
          <span class="blue-line"> | </span>
          <span>友達を検索</span>
          <span class="blue-line"> | </span>
          <span>作成</span>
          <span class="blue-line"> | </span>
          <span>うに</span>
          <span class="blue-line"> | </span>
          <span>
          <%= link_to "ログアウト", session_path(current_user.id), method: :delete %>
          <% else %>
            <%= link_to "登録", new_user_path %>
            <%= link_to "ログイン", new_session_path %>
          <% end %>
          </span>
        </div>
      </td>
    </tr>
  </table>
</header>

<main>
  <div class="general-box">
    <h2>投稿を作成</h2>
    <%= render 'form' %>
  </div>
</main>

app/views/blogs/show.html.erb
<header>
  <table>
    <tr>
      <td><%= image_tag "facebook.png", class: 'fakebook-logo' %></td>
      <td>
        <div class="fake-search-box">
          <div class="search-sujest">検索</div>
          <div class="search-content"></div>
          <div class="search-img"><%= image_tag "Search.png", class: 'search-png' %></div>
        </div>
      </td>
      <td><%= image_tag "acount-pic.png", size: '25x25', class: 'header-acount-pic' %></td>
      <td>
        <div class="header-menu">
          <% flash.each do |key, value| %>
            <%= content_tag(:div, value, class: "#{key}") %>
          <% end %>
          <span>
          <% if logged_in? %>
            <%= link_to "#{current_user.name}", user_path(current_user.id) %>
          </span>
          <span class="blue-line"> | </span>
          <span>
            <%= link_to "ホーム", blogs_path %>
          </span>
          <span class="blue-line"> | </span>
          <span>友達を検索</span>
          <span class="blue-line"> | </span>
          <span>作成</span>
          <span class="blue-line"> | </span>
          <span>うに</span>
          <span class="blue-line"> | </span>
          <span>
          <%= link_to "Logout", session_path(current_user.id), method: :delete %>
          <% else %>
            <%= link_to "サインアップ", new_user_path %>
            <%= link_to "ログイン", new_session_path %>
          <% end %>
          </span>
        </div>
      </td>
    </tr>
  </table>
</header>

<main>
  <div class="detail-box">
    <h1>詳細ページ</h1>
    <p><%= @blog.content %></p>
    <p>
      <% if @blog.image.file.nil? %>
      <% else %>
        <%= image_tag @blog.image.url %>
      <% end %>
    </p>
    <%= link_to '編集', edit_blog_path(@blog) %> |
    <%= link_to '戻る', blogs_path %>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FakebookApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<header>
  <table>
    <tr>
      <td><%= image_tag "facebook.png", class: 'fakebook-logo' %></td>
      <td>
        <div class="fake-search-box">
          <div class="search-sujest">検索</div>
          <div class="search-content"></div>
          <div class="search-img"><%= image_tag "Search.png", class: 'search-png' %></div>
        </div>
      </td>
      <td> </td>
      <td>
        <div class="header-menu">
          <% flash.each do |key, value| %>
            <%#= content_tag(:div, value, class: "#{key}") %>
          <% end %>
          <span>
          <% if logged_in? %>
            <%= link_to "#{current_user.name}", user_path(current_user.id) %>
          </span>
          <span class="blue-line"> | </span>
          <span>
            <%= link_to "ホーム", blogs_path %>
          </span>
          <span class="blue-line"> | </span>
          <span>友達を検索</span>
          <span class="blue-line"> | </span>
          <span>作成</span>
          <span class="blue-line"> | </span>
          <span>うに</span>
          <span class="blue-line"> | </span>
          <span>
          <%= link_to "Logout", session_path(current_user.id), method: :delete %>
          <% else %>
            <%= link_to "登録", new_user_path %>
            <%= link_to "ログイン", new_session_path %>
          <% end %>
          </span>
        </div>
      </td>
    </tr>
  </table>
</header>

<main>
  <div class="general-box">
    <h1>登録</h1>
    <p>※アカウント名は最大9文字まで</p>
    <p>※パスワードは最低6文字以上</p>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
        <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <%= form_with(model: @user, local: true) do |f| %>  
      <%= f.label :name, 'アカウント名' %>
      <%= f.text_field :name %>

      <%= f.label :email, 'E-mailアドレス' %>
      <%= f.email_field :email %>

      <%= f.label :password, 'パスワード' %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, 'パスワード(確認)' %>
      <%= f.password_field :password_confirmation %>
      <br>
      <br>
      <p><%= f.submit "アカウントを作成" %></p>
    <% end %>
  </div>
</main>

app/views/users/show.html.erb
<header>
  <table>
    <tr>
      <td><%= image_tag "facebook.png", class: 'fakebook-logo' %></td>
      <td>
        <div class="fake-search-box">
          <div class="search-sujest">検索</div>
          <div class="search-content"></div>
          <div class="search-img"><%= image_tag "Search.png", class: 'search-png' %></div>
        </div>
      </td>
      <td><%= image_tag "acount-pic.png", size: '25x25', class: 'header-acount-pic' %></td>
      <td>
        <div class="header-menu">
          <% flash.each do |key, value| %>
            <%#= content_tag(:div, value, class: "#{key}") %>
          <% end %>
          <span>
          <% if logged_in? %>
            <%= link_to "#{current_user.name}", user_path(current_user.id) %>
          </span>
          <span class="blue-line"> | </span>
          <span>
            <%= link_to "ホーム", blogs_path %>
          </span>
          <span class="blue-line"> | </span>
          <span>友達を検索</span>
          <span class="blue-line"> | </span>
          <span>作成</span>
          <span class="blue-line"> | </span>
          <span>うに</span>
          <span class="blue-line"> | </span>
          <span>
          <%= link_to "ログアウト", session_path(current_user.id), method: :delete %>
          <% else %>
            <%= link_to "登録", new_user_path %>
            <%= link_to "ログイン", new_session_path %>
          <% end %>
          </span>
        </div>
      </td>
    </tr>
  </table>
</header>

<main>
  <div class="profile">
    <h1><%= @user.name %>のプロフィール</h1>
    <span><%= image_tag "acount-pic.png", size: '300x300', class: 'profile-acount-pic' %></span>
    <p>メールアドレス: <%= @user.email %></p>
  </div>
</main>